### ISSUE TITLE
Provide some sample configuration

### ISSUE THREAD

**Issue by boydlee** [leeboy1984/aws-lambda-s3-kraken#1]
Would be great to provide a sample configuration set for reference (with any keys XXXX'd out for obvious reasons) ... some of the config variables such as params.url are not very clear. It also looks as though your sample configuration has the AWS and KRAKEN notes attached to the incorrect config parameters?

  I am trying to implement this, but so far just getting HTTP 401 errors - _**HTTPError: HTTP Error 401: Unauthorized**_

**Comment by leeboy1984** [comment]
Hi!

My apologies, the keys were wrong. I have fixed the code. Could you please review? if not sure we can talk directly via email

**Comment by boydlee** [comment]
Perfect, works great for me now!

Great name btw, like mine, only backwards ;)
